name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld cmake ninja-build grub-pc-bin grub-efi-amd64-bin xorriso mtools
      - name: Build
        run: |
          ./scripts/build.sh
      - name: Make ISO
        run: |
          ./scripts/make_iso.sh
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-os-iso
          path: build/hello-os.iso
